create table if not exists public.assets (
    id bigint generated by default as identity primary key,
    category text not null,
    account text not null unique,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.asset_values (
    id bigint generated by default as identity primary key,
    asset_id bigint not null references public.assets(id) on delete cascade,
    snapshot_date date not null,
    amount numeric(18,4) not null,
    updated_at timestamptz not null default now(),
    unique (asset_id, snapshot_date)
);

create index if not exists idx_asset_values_snapshot_date on public.asset_values (snapshot_date);
create index if not exists idx_asset_values_asset_id on public.asset_values (asset_id);
